//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 11:43:37 AM CET 
//


package eu.kmd.opus;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}entryDate"/>
 *         &lt;element ref="{}leaveDate"/>
 *         &lt;element ref="{}cpr"/>
 *         &lt;element ref="{}firstName"/>
 *         &lt;element ref="{}lastName"/>
 *         &lt;element ref="{}address"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}addressSupplement" minOccurs="0"/>
 *           &lt;element ref="{}postalCode"/>
 *           &lt;element ref="{}city"/>
 *           &lt;element ref="{}country"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}workPhone"/>
 *         &lt;element ref="{}workContract"/>
 *         &lt;element ref="{}workContractText" minOccurs="0"/>
 *         &lt;element ref="{}positionId"/>
 *         &lt;element ref="{}position"/>
 *         &lt;element ref="{}positionShort"/>
 *         &lt;element ref="{}jobId"/>
 *         &lt;element ref="{}job"/>
 *         &lt;element ref="{}jobShort"/>
 *         &lt;element ref="{}itUser"/>
 *         &lt;element ref="{}invoiceRecipient"/>
 *         &lt;element ref="{}invoiceLevel1" minOccurs="0"/>
 *         &lt;element ref="{}invoiceLevel1Text" minOccurs="0"/>
 *         &lt;element ref="{}invoiceLevel2" minOccurs="0"/>
 *         &lt;element ref="{}invoiceLevel2Text" minOccurs="0"/>
 *         &lt;element ref="{}productionNumber"/>
 *         &lt;element ref="{}isManager"/>
 *         &lt;element ref="{}superiorLevel"/>
 *         &lt;element ref="{}subordinateLevel"/>
 *         &lt;element name="orgUnit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}email" minOccurs="0"/>
 *         &lt;element ref="{}userId" minOccurs="0"/>
 *         &lt;element ref="{}payGradeText"/>
 *         &lt;element ref="{}numerator"/>
 *         &lt;element ref="{}denominator"/>
 *         &lt;element ref="{}initialEntry"/>
 *         &lt;element ref="{}entryIntoGroup"/>
 *         &lt;element ref="{}function" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lastChanged" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="client" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
"entryDate",
"leaveDate",
"cpr",
"firstName",
"lastName",
"address",
"addressSupplement",
"postalCode",
"city",
"country",
"workPhone",
"workContract",
"workContractText",
"positionId",
"position",
"positionShort",
"jobId",
"job",
"jobShort",
"itUser",
"invoiceRecipient",
"invoiceLevel1",
"invoiceLevel1Text",
"invoiceLevel2",
"invoiceLevel2Text",
"productionNumber",
"isManager",
"superiorLevel",
"subordinateLevel",
"orgUnit",
"email",
"userId",
"payGradeText",
"numerator",
"denominator",
"initialEntry",
"entryIntoGroup",
"function"
})
@XmlRootElement(name = "employee")
public class Employee
{

    protected String entryDate;
    protected String leaveDate;
    protected Cpr cpr;
    protected String firstName;
    protected String lastName;
    protected Address address;
    protected String addressSupplement;
    protected String postalCode;
    protected String city;
    protected String country;
    protected String workPhone;
    protected String workContract;
    protected String workContractText;
    protected Integer positionId;
    protected String position;
    protected String positionShort;
    protected Integer jobId;
    protected String job;
    protected String jobShort;
    protected String itUser;
    protected Boolean invoiceRecipient;
    protected String invoiceLevel1;
    protected String invoiceLevel1Text;
    protected String invoiceLevel2;
    protected String invoiceLevel2Text;
    protected String productionNumber;
    protected Boolean isManager;
    protected Byte superiorLevel;
    protected Byte subordinateLevel;
    protected Integer orgUnit;
    protected String email;
    protected String userId;
    protected String payGradeText;
    protected BigDecimal numerator;
    protected BigDecimal denominator;
    protected String initialEntry;
    protected String entryIntoGroup;
    protected List<Function> function;
    @XmlAttribute(name = "lastChanged")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastChanged;
    @XmlAttribute(name = "id", required = true)
    protected int id;
    @XmlAttribute(name = "client", required = true)
    protected short client;
    @XmlAttribute(name = "action")
    protected String action;

    /**
     * Gets the value of the entryDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEntryDate()
    {
        return entryDate;
    }

    /**
     * Sets the value of the entryDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEntryDate(String value)
    {
        this.entryDate = value;
    }

    /**
     * Gets the value of the leaveDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLeaveDate()
    {
        return leaveDate;
    }

    /**
     * Sets the value of the leaveDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLeaveDate(String value)
    {
        this.leaveDate = value;
    }

    /**
     * Gets the value of the cpr property.
     *
     * @return possible object is
     * {@link Cpr }
     */
    public Cpr getCpr()
    {
        return cpr;
    }

    /**
     * Sets the value of the cpr property.
     *
     * @param value allowed object is
     *              {@link Cpr }
     */
    public void setCpr(Cpr value)
    {
        this.cpr = value;
    }

    /**
     * Gets the value of the firstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFirstName()
    {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFirstName(String value)
    {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastName()
    {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastName(String value)
    {
        this.lastName = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link Address }
     */
    public Address getAddress()
    {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link Address }
     */
    public void setAddress(Address value)
    {
        this.address = value;
    }

    /**
     * Gets the value of the addressSupplement property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddressSupplement()
    {
        return addressSupplement;
    }

    /**
     * Sets the value of the addressSupplement property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddressSupplement(String value)
    {
        this.addressSupplement = value;
    }

    /**
     * Gets the value of the postalCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostalCode()
    {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostalCode(String value)
    {
        this.postalCode = value;
    }

    /**
     * Gets the value of the city property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCity()
    {
        return city;
    }

    /**
     * Sets the value of the city property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCity(String value)
    {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountry()
    {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountry(String value)
    {
        this.country = value;
    }

    /**
     * Gets the value of the workPhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWorkPhone()
    {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWorkPhone(String value)
    {
        this.workPhone = value;
    }

    /**
     * Gets the value of the workContract property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWorkContract()
    {
        return workContract;
    }

    /**
     * Sets the value of the workContract property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWorkContract(String value)
    {
        this.workContract = value;
    }

    /**
     * Gets the value of the workContractText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWorkContractText()
    {
        return workContractText;
    }

    /**
     * Sets the value of the workContractText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWorkContractText(String value)
    {
        this.workContractText = value;
    }

    /**
     * Gets the value of the positionId property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getPositionId()
    {
        return positionId;
    }

    /**
     * Sets the value of the positionId property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setPositionId(Integer value)
    {
        this.positionId = value;
    }

    /**
     * Gets the value of the position property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPosition()
    {
        return position;
    }

    /**
     * Sets the value of the position property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPosition(String value)
    {
        this.position = value;
    }

    /**
     * Gets the value of the positionShort property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPositionShort()
    {
        return positionShort;
    }

    /**
     * Sets the value of the positionShort property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPositionShort(String value)
    {
        this.positionShort = value;
    }

    public Integer getJobId()
    {
        return jobId;
    }
    public void setJobId(Integer value)
    {
        this.jobId = value;
    }
    public String getJob()
    {
        return job;
    }
    public void setJob(String value)
    {
        this.job = value;
    }
    public String getJobShort()
    {
        return jobShort;
    }
    public void setJobshort(String value)
    {
        this.jobShort = value;
    }
    public String getItUser()
    {
        return itUser;
    }
    public void setItUser(String value)
    {
        this.itUser = value;
    }




    /**
     * Gets the value of the invoiceRecipient property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isInvoiceRecipient()
    {
        return invoiceRecipient;
    }

    /**
     * Sets the value of the invoiceRecipient property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setInvoiceRecipient(Boolean value)
    {
        this.invoiceRecipient = value;
    }

    /**
     * Gets the value of the invoiceLevel1 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInvoiceLevel1()
    {
        return invoiceLevel1;
    }

    /**
     * Sets the value of the invoiceLevel1 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInvoiceLevel1(String value)
    {
        this.invoiceLevel1 = value;
    }

    /**
     * Gets the value of the invoiceLevel1Text property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInvoiceLevel1Text()
    {
        return invoiceLevel1Text;
    }

    /**
     * Sets the value of the invoiceLevel1Text property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInvoiceLevel1Text(String value)
    {
        this.invoiceLevel1Text = value;
    }

    /**
     * Gets the value of the invoiceLevel2 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInvoiceLevel2()
    {
        return invoiceLevel2;
    }

    /**
     * Sets the value of the invoiceLevel2 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInvoiceLevel2(String value)
    {
        this.invoiceLevel2 = value;
    }

    /**
     * Gets the value of the invoiceLevel2Text property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInvoiceLevel2Text()
    {
        return invoiceLevel2Text;
    }

    /**
     * Sets the value of the invoiceLevel2Text property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInvoiceLevel2Text(String value)
    {
        this.invoiceLevel2Text = value;
    }

    /**
     * Gets the value of the productionNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductionNumber()
    {
        return productionNumber;
    }

    /**
     * Sets the value of the productionNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductionNumber(String value)
    {
        this.productionNumber = value;
    }

    /**
     * Gets the value of the isManager property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsManager()
    {
        return isManager;
    }

    /**
     * Sets the value of the isManager property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsManager(Boolean value)
    {
        this.isManager = value;
    }

    /**
     * Gets the value of the superiorLevel property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getSuperiorLevel()
    {
        return superiorLevel;
    }

    /**
     * Sets the value of the superiorLevel property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setSuperiorLevel(Byte value)
    {
        this.superiorLevel = value;
    }

    /**
     * Gets the value of the subordinateLevel property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getSubordinateLevel()
    {
        return subordinateLevel;
    }

    /**
     * Sets the value of the subordinateLevel property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setSubordinateLevel(Byte value)
    {
        this.subordinateLevel = value;
    }

    /**
     * Gets the value of the orgUnit property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getOrgUnit()
    {
        return orgUnit;
    }

    /**
     * Sets the value of the orgUnit property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setOrgUnit(Integer value)
    {
        this.orgUnit = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value)
    {
        this.email = value;
    }

    /**
     * Gets the value of the userId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserId()
    {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserId(String value)
    {
        this.userId = value;
    }

    /**
     * Gets the value of the payGradeText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPayGradeText()
    {
        return payGradeText;
    }

    /**
     * Sets the value of the payGradeText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPayGradeText(String value)
    {
        this.payGradeText = value;
    }

    /**
     * Gets the value of the numerator property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getNumerator()
    {
        return numerator;
    }

    /**
     * Sets the value of the numerator property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setNumerator(BigDecimal value)
    {
        this.numerator = value;
    }

    /**
     * Gets the value of the denominator property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getDenominator()
    {
        return denominator;
    }

    /**
     * Sets the value of the denominator property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setDenominator(BigDecimal value)
    {
        this.denominator = value;
    }

    /**
     * Gets the value of the initialEntry property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInitialEntry()
    {
        return initialEntry;
    }

    /**
     * Sets the value of the initialEntry property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInitialEntry(String value)
    {
        this.initialEntry = value;
    }

    /**
     * Gets the value of the entryIntoGroup property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEntryIntoGroup()
    {
        return entryIntoGroup;
    }

    /**
     * Sets the value of the entryIntoGroup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEntryIntoGroup(String value)
    {
        this.entryIntoGroup = value;
    }

    /**
     * Gets the value of the function property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the function property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunction().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Function }
     */
    public List<Function> getFunction()
    {
        if (function == null)
        {
            function = new ArrayList<Function>();
        }
        return this.function;
    }

    /**
     * Gets the value of the lastChanged property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getLastChanged()
    {
        return lastChanged;
    }

    /**
     * Sets the value of the lastChanged property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setLastChanged(XMLGregorianCalendar value)
    {
        this.lastChanged = value;
    }

    /**
     * Gets the value of the id property.
     */
    public int getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(int value)
    {
        this.id = value;
    }

    /**
     * Gets the value of the client property.
     */
    public short getClient()
    {
        return client;
    }

    /**
     * Sets the value of the client property.
     */
    public void setClient(short value)
    {
        this.client = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAction()
    {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAction(String value)
    {
        this.action = value;
    }

}
