//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 11:43:37 AM CET 
//


package eu.kmd.opus;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}orgDaekning"/>
 *         &lt;element ref="{}artText"/>
 *         &lt;element ref="{}members"/>
 *         &lt;element ref="{}roleId"/>
 *         &lt;element ref="{}roleText" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="startDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="endDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="artId" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
"orgDaekning",
"artText",
"members",
"roleId",
"roleText"
})
@XmlRootElement(name = "function")
public class Function
{

    @XmlElement(required = true)
    protected String orgDaekning;
    @XmlElement(required = true)
    protected String artText;
    protected byte members;
    protected int roleId;
    protected String roleText;
    @XmlAttribute(name = "startDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute(name = "endDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlAttribute(name = "artId", required = true)
    protected short artId;

    /**
     * Gets the value of the orgDaekning property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrgDaekning()
    {
        return orgDaekning;
    }

    /**
     * Sets the value of the orgDaekning property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrgDaekning(String value)
    {
        this.orgDaekning = value;
    }

    /**
     * Gets the value of the artText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArtText()
    {
        return artText;
    }

    /**
     * Sets the value of the artText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setArtText(String value)
    {
        this.artText = value;
    }

    /**
     * Gets the value of the members property.
     */
    public byte getMembers()
    {
        return members;
    }

    /**
     * Sets the value of the members property.
     */
    public void setMembers(byte value)
    {
        this.members = value;
    }

    /**
     * Gets the value of the roleId property.
     */
    public int getRoleId()
    {
        return roleId;
    }

    /**
     * Sets the value of the roleId property.
     */
    public void setRoleId(int value)
    {
        this.roleId = value;
    }

    /**
     * Gets the value of the roleText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoleText()
    {
        return roleText;
    }

    /**
     * Sets the value of the roleText property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoleText(String value)
    {
        this.roleText = value;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getStartDate()
    {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStartDate(XMLGregorianCalendar value)
    {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEndDate()
    {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEndDate(XMLGregorianCalendar value)
    {
        this.endDate = value;
    }

    /**
     * Gets the value of the artId property.
     */
    public short getArtId()
    {
        return artId;
    }

    /**
     * Sets the value of the artId property.
     */
    public void setArtId(short value)
    {
        this.artId = value;
    }

}
