//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.13 at 11:43:37 AM CET 
//


package eu.kmd.opus;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}startDate" minOccurs="0"/>
 *         &lt;element ref="{}endDate" minOccurs="0"/>
 *         &lt;element ref="{}parentOrgUnit"/>
 *         &lt;element ref="{}shortName"/>
 *         &lt;element ref="{}longName"/>
 *         &lt;element ref="{}street"/>
 *         &lt;element ref="{}addressSupplement" minOccurs="0"/>
 *         &lt;element ref="{}zipCode"/>
 *         &lt;element ref="{}city"/>
 *         &lt;element ref="{}phoneNumber"/>
 *         &lt;element ref="{}cvrNr" minOccurs="0"/>
 *         &lt;element ref="{}eanNr" minOccurs="0"/>
 *         &lt;element ref="{}seNr" minOccurs="0"/>
 *         &lt;element ref="{}pNr" minOccurs="0"/>
 *         &lt;element ref="{}costCenter" minOccurs="0"/>
 *         &lt;element ref="{}orgType" minOccurs="0"/>
 *         &lt;element ref="{}orgTypeTxt" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lastChanged" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="client" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
"startDate",
"endDate",
"parentOrgUnit",
"shortName",
"longName",
"street",
"addressSupplement",
"zipCode",
"city",
"phoneNumber",
"cvrNr",
"eanNr",
"seNr",
"pNr",
"costCenter",
"orgType",
"orgTypeTxt"
})
@XmlRootElement(name = "orgUnit")
public class OrgUnit
{

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    protected String parentOrgUnit;
    protected String shortName;
    protected String longName;
    protected String street;
    protected String addressSupplement;
    protected Short zipCode;
    protected String city;
    protected String phoneNumber;
    protected Integer cvrNr;
    protected Long eanNr;
    protected Integer seNr;
    protected Integer pNr;
    protected Long costCenter;
    protected Byte orgType;
    protected String orgTypeTxt;
    @XmlAttribute(name = "lastChanged")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastChanged;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "client")
    protected Short client;

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getStartDate()
    {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStartDate(XMLGregorianCalendar value)
    {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEndDate()
    {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEndDate(XMLGregorianCalendar value)
    {
        this.endDate = value;
    }

    /**
     * Gets the value of the parentOrgUnit property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getParentOrgUnit()
    {
        return parentOrgUnit;
    }

    /**
     * Sets the value of the parentOrgUnit property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setParentOrgUnit(String value)
    {
        this.parentOrgUnit = value;
    }

    /**
     * Gets the value of the shortName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getShortName()
    {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setShortName(String value)
    {
        this.shortName = value;
    }

    /**
     * Gets the value of the longName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLongName()
    {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLongName(String value)
    {
        this.longName = value;
    }

    /**
     * Gets the value of the street property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStreet()
    {
        return street;
    }

    /**
     * Sets the value of the street property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStreet(String value)
    {
        this.street = value;
    }

    /**
     * Gets the value of the addressSupplement property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddressSupplement()
    {
        return addressSupplement;
    }

    /**
     * Sets the value of the addressSupplement property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddressSupplement(String value)
    {
        this.addressSupplement = value;
    }

    /**
     * Gets the value of the zipCode property.
     *
     * @return possible object is
     * {@link Short }
     */
    public Short getZipCode()
    {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     *
     * @param value allowed object is
     *              {@link Short }
     */
    public void setZipCode(Short value)
    {
        this.zipCode = value;
    }

    /**
     * Gets the value of the city property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCity()
    {
        return city;
    }

    /**
     * Sets the value of the city property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCity(String value)
    {
        this.city = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhoneNumber(String value)
    {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the cvrNr property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getCvrNr()
    {
        return cvrNr;
    }

    /**
     * Sets the value of the cvrNr property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setCvrNr(Integer value)
    {
        this.cvrNr = value;
    }

    /**
     * Gets the value of the eanNr property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getEanNr()
    {
        return eanNr;
    }

    /**
     * Sets the value of the eanNr property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setEanNr(Long value)
    {
        this.eanNr = value;
    }

    /**
     * Gets the value of the seNr property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getSeNr()
    {
        return seNr;
    }

    /**
     * Sets the value of the seNr property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setSeNr(Integer value)
    {
        this.seNr = value;
    }

    /**
     * Gets the value of the pNr property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getPNr()
    {
        return pNr;
    }

    /**
     * Sets the value of the pNr property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setPNr(Integer value)
    {
        this.pNr = value;
    }

    /**
     * Gets the value of the costCenter property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getCostCenter()
    {
        return costCenter;
    }

    /**
     * Sets the value of the costCenter property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setCostCenter(Long value)
    {
        this.costCenter = value;
    }

    /**
     * Gets the value of the orgType property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getOrgType()
    {
        return orgType;
    }

    /**
     * Sets the value of the orgType property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setOrgType(Byte value)
    {
        this.orgType = value;
    }

    /**
     * Gets the value of the orgTypeTxt property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrgTypeTxt()
    {
        return orgTypeTxt;
    }

    /**
     * Sets the value of the orgTypeTxt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrgTypeTxt(String value)
    {
        this.orgTypeTxt = value;
    }

    /**
     * Gets the value of the lastChanged property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getLastChanged()
    {
        return lastChanged;
    }

    /**
     * Sets the value of the lastChanged property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setLastChanged(XMLGregorianCalendar value)
    {
        this.lastChanged = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setId(String value)
    {
        this.id = value;
    }

    /**
     * Gets the value of the client property.
     *
     * @return possible object is
     * {@link Short }
     */
    public Short getClient()
    {
        return client;
    }

    /**
     * Sets the value of the client property.
     *
     * @param value allowed object is
     *              {@link Short }
     */
    public void setClient(Short value)
    {
        this.client = value;
    }

}
